### ISSUE TITLE
I don't see any parsing

### ISSUE THREAD

**Issue by TheColonel2688** [haakonnessjoen/iecstruct#1]
I was looking for a solution that would take an ST Struct source code and create a Buffer encoder/decoder for that type in another language.

From looking at the source code I don't see any parsing happening only encode and decode. 

am I missing something here?

**Comment by haakonnessjoen** [comment]
No, this doesn't parse it, you need to recreate it with code.

I did some playing around to parse too, but I don't remember how far I got, it's not finished by any means:
https://github.com/haakonnessjoen/iectype-parser
